import { Beaker } from 'lucide-react'
import { ReportPageBlock } from './ReportShell'
import type { Project } from '@/types'

const DESIGN_LABEL: Record<string, string> = {
  full_factorial: 'Full factorial',
  fractional_factorial: 'Fractional factorial',
  plackett_burman: 'Plackett–Burman',
  ccd: 'Central composite design',
  box_behnken: 'Box–Behnken',
  definitive_screening: 'Definitive screening',
  optimal_d: 'D-optimal',
  optimal_i: 'I-optimal',
  simplex_lattice: 'Simplex lattice mixture',
  simplex_centroid: 'Simplex centroid mixture',
  latin_hypercube: 'Latin hypercube',
}

export function CoverPage({ project }: { project: Project }) {
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  return (
    <ReportPageBlock id="cover" cover>
      <div className="flex items-center gap-3 mb-8">
        <div className="grid h-12 w-12 place-items-center rounded-xl bg-primary text-primary-foreground shadow-token-md">
          <Beaker className="h-6 w-6" />
        </div>
        <div>
          <div className="text-eyebrow">DOE Lab — Experiment Report</div>
          <div className="text-[12px] text-muted-foreground">{today}</div>
        </div>
      </div>

      <div>
        <h1 className="report-h1">{project.name}</h1>
        <div className="text-[14px] text-muted-foreground mt-1">
          {DESIGN_LABEL[project.designType] ?? project.designType.replace(/_/g, ' ')}
        </div>
      </div>

      <div className="grid grid-cols-2 gap-3 mt-10 max-w-md">
        <Stat label="Runs" value={String(project.designRows.length)} />
        <Stat label="Factors" value={String(project.factors.length)} />
        <Stat label="Responses" value={String(project.responses.length)} />
        <Stat label="Center points" value={String(project.designRows.filter((r) => r.point_type === 'center').length)} />
      </div>

      <div className="mt-12 report-meta">
        Generated by DOE Lab — open-source design-of-experiments suite.
      </div>
    </ReportPageBlock>
  )
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-border-soft bg-white/60 backdrop-blur-sm px-4 py-3">
      <div className="text-eyebrow">{label}</div>
      <div className="mono text-2xl font-semibold mt-1">{value}</div>
    </div>
  )
}
